const Constants = {
  // Filters
  FILTER_LOW_PRIORITY: "FILTER_LOW_PRIORITY",
  FILTER_MEDIUM_PRIORITY: "FILTER_MEDIUM_PRIORITY",
  FILTER_HIGH_PRIORITY: "FILTER_HIGH_PRIORITY",

  // Sort
  SORT_HIGH_TO_LOW: "SORT_HIGH_TO_LOW",
  SORT_LOW_TO_HIGH: "SORT_LOW_TO_HIGH",
  SORT_NEWEST_TO_OLDEST: "SORT_NEWEST_TO_OLDEST",
  SORT_OLDEST_TO_NEWEST: "SORT_OLDEST_TO_NEWEST",
}

export default Constants;
